### ISSUE TITLE
Incorrect plural form when using base language different from EN

### ISSUE THREAD

**Issue by noisette44** [rubenv/angular-gettext#182]
When I use a base language different from "EN" (for exemple "FR") the plurial form is always use "EN" base language (n === 1 ? string : stringPlural)

Code in "getPlural" function: 
string = this.getStringForm(string, form, context) || prefixDebug(n === 1 ? string : stringPlural);

Probable correction:
string = this.getStringForm(string, form, context) || prefixDebug(form ? stringPlural : string);

Thanks.

**Comment by rubenv** [comment]
That won't work for any language that has more than two forms.

I *strongly* recommend against using anything other than English as a base language. Just don't do it.

**Comment by noisette44** [comment]
Extact, this correction will not work for any language that has more than two forms...
I agree with you about using English as a base language is the best pratice but when the application is initially developed in another language it's not easy to change it.

**Comment by Yappli** [comment]
It's clearly a problem. In french 0 is not a plural.

**Comment by Yappli** [comment]
``` gettextPlurals``` is clearly the only one way we must use to define what is plural or not.

As long as ``` form``` is available here, it will definitively be a better choice to use it than make the second comparison ``` n === 1```.

Of course, this doesn't provide a perfect solution for languages has more than 2 plural forms but ``` n === 1``` is even worse.

**Comment by rubenv** [comment]
I'm sorry, I'm not planning on supporting this.

You are right, we could do this easy fix. But every tool that handles `.po` files is designed around the fact that the base language is English. Supporting alternate base language is a bad idea: subtle differences in assumptions will cause breakage.

Angular-gettext is opinionated: there's only one way to do things and that's the right way. Why? Because this way the only way of working is the way that will produce correct results.

Allowing alternative languages will lead to bugs (subtle and hard to fix bugs) for users who do not fully understand which trouble they're getting into.
