### ISSUE TITLE
Arabic language support not working

### ISSUE THREAD

**Issue by ommaralquisi** [rubenv/angular-gettext#260]
Strange issue here... seemingly all languages are working except Arabic.
```javascript
gettextCatalog.currentLanguage = 'ar';
```
Results in all strings not to be translated. However, changing to the po language tag to e.g. "ara" seems to solve it. Any idea why "ar" is not working?

**Comment by azizantoun** [comment]
Same issue happening to me. Renaming translation to ara or anything else worked. I'm using Angular 1.5

**Comment by freiserg** [comment]
I have same problem. Language variables was translated only in javascript files. In html it isn't translated.

**Comment by alafi** [comment]
Greetings...

I believe that I found the issue here:
The default value of parameter `n` passed to `getString` in catalog.js is `1`. Now refering to the plural expression of Arabic:

> (n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5)

and when `n==1` it returns 1, which means gettext will select the second item in the translation array. So if there is only a single translation value for the entry, it will be at index 0 and will never show up.
A workaround for this is to always add `translate-n="0" translate-plural="{{$count}}"` whenever no plural translation is needed.

Hope that this issue will get attention and someone will provide a better solution.

**Comment by KevinLandsberg** [comment]
Is there any workaround which does not break the support for other languages?
If i add the pluralization workaround mentioned by @alafi the other languages are not translated anymore.

**Comment by KevinLandsberg** [comment]
The same problem occures with the "Slovenian" language.

**Comment by fix** [comment]
+1 this needs to be fixed asap imho
