### ISSUE TITLE
Extracting - translated variables

### ISSUE THREAD

**Issue by SamanthaAdrichem** [rubenv/angular-gettext#274]
Whats the best practise to extracting translated variables?

for example i have {{user.status | translate}} now what should be translated are the words "active" and "inactive".

is there for example a comment annotation for?  (or javascript // @translate comment )

or is it best to create a dummy line in the files saying gettextCatalog.getString();

**Comment by rubenv** [comment]
Annotate the assignment to `user.status` with `gettext()`: https://angular-gettext.rocketeer.be/dev-guide/annotate-js/

```js
$scope.user.status = gettext("active");
```

**Comment by SamanthaAdrichem** [comment]
The status comes from the API, so it's dynamically. So basically it would mean that i have to do a switch?

`
switch( $scope.user.status ) {
  case 'active:
    $scope.user.status = gettext("active");
    break;
}

`

**Comment by rubenv** [comment]
Yup, it's ugly but it works. There needs to be some way to indicate translatable strings since angular-gettext doesn't know anything about the strings that'll be returned from the backend.

You can write it shorter though:

```js
var statuscodes = {
    active: gettext("active"),
    inactive: gettext("inactive"),
};
$scope.user.status = statuscodes[code_from_backend] || code_from_backend;
```

This one also falls back to whatever the backend returns in case the frontend doesn't know it.

**Comment by SamanthaAdrichem** [comment]
Ok thnx!
